### ISSUE TITLE
Does not work in Browserify

### ISSUE THREAD

**Issue by dwighthouse** [alanshaw/stripify#3] opened 2015-11-18 16:07 UTC
This transform no longer appears to work with current versions of Browserify. All your tests ran successfully, but in my project (Browserify+Gulp), the output with and without stripify transform is identical.

I also tried it via command line as a browserify transform. This is the command I ran:
```
./node_modules/.bin/browserify -t stripify ./vendor.js > test.js
```
The resulting `test.js` contains console statements.

My version of Browserify is `12.0.1`.

**Comment by nolanlawson** [comment] 2016-01-11 21:31
Do you have a test file to reproduce? I can't reproduce using stripify 3.0.0 and browesrify 11.2.0. I have a simple file like:

```
console.log('hello world');
```

And it's stripping that out...

**Comment by alanshaw** [comment] 2016-01-21 20:50
Closing as I cannot reproduce using stripify 4.0.0 and browserify 12.0.1 or browserify 13.0.0 (latest)

**Closed by alanshaw** 2016-01-21 20:50 UTC

**Comment by dwighthouse** [comment] 2016-01-26 21:17
Sorry for taking so long to respond, I somehow didn't see your responses.

An example file that fails to work is as follows:

```
'use strict';

// Console statements in this dependency WILL be removed
var Dep = require('./dependency.js');

// Console statements in this dependency WILL NOT be removed???
var React = require('react');

module.exports = function() {
    var counter = 0;
    counter += 1;

    // Will be removed
    console.log(counter);

    while (counter < 20)
    {
        counter += 3;

        // Will be removed
        console.log(counter);
    }
};
```

This was built with the gulpfile:

```
'use strict';

var gulp = require('gulp');
var browserify = require('browserify');
var vinylSourceStream = require('vinyl-source-stream');
var vinylBuffer = require('vinyl-buffer');

gulp.task('standard', function() {
    var bundler = browserify({
        entries: ['./StripifyTest.js'],
        transform: [
            ['stripify', {
                replacement: '(0)'
            }]
        ]
    });

    return bundler.bundle()
    .on('error', function(error) {
        console.error(error);
        this.emit('end');
    })
    .pipe(vinylSourceStream('StripifyTest.stripped.js'))
    .pipe(vinylBuffer())
    .pipe(gulp.dest('./'));
});
```

Any dependencies imported as named dependencies (not local dependencies) [will not be transformed by any Browserify transforms](https://github.com/substack/node-browserify/issues/605), by default. This behavior is by design in Browserify. Since I was only testing Stripify on my vendor/third-party file, I noticed no effect when using Stripify on my project.

The solution is to make sure that the `global: true` value is set in the transform properties. This will apply the transform to all dependencies. In my gulpfile, the working solution would look like this:

```
'use strict';

var gulp = require('gulp');
var browserify = require('browserify');
var vinylSourceStream = require('vinyl-source-stream');
var vinylBuffer = require('vinyl-buffer');

gulp.task('standard', function() {
    var bundler = browserify({
        entries: ['./StripifyTest.js'],
        transform: [
            ['stripify', {
                replacement: '(0)',
                global: true
            }]
        ]
    });

    return bundler.bundle()
    .on('error', function(error) {
        console.error(error);
        this.emit('end');
    })
    .pipe(vinylSourceStream('StripifyTest.stripped.js'))
    .pipe(vinylBuffer())
    .pipe(gulp.dest('./'));
});
```

So, this is not a problem with Stripify, but with Browserify. However, given that this is a Browserify transform, it might be a good idea to mention in the docs that...

> When used as a Browserify transform, Stripify will not perform any actions on named dependancies unless the `global` option is set to `true`.

And then provide some examples.
